version: '2'

networks:
  traefik:
    external:
      name: traefik_webgateway

services:

  yarn:
    image: node:8.2
    volumes:
      - ./:/var/www/bitterballen
    working_dir: /var/www/bitterballen
    ports:
      - 3000:3000
    command: yarn start
    environment:
      - REACT_APP_API_SERVER=https://bitterballen-api.scriptcie.nl

  npm:
    image: node:8.2
    volumes:
      - ./:/var/www/bitterballen
    working_dir: /var/www/bitterballen
    command: yarn start
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=bitterballen-client-web"
      - "traefik.frontend.rule=Host:bitterballen.scriptcie.nl.localhost, bitterballen.dev"
      - "traefik.port=3000"
      - "traefik.docker.network=traefik_webgateway"
